name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      - name: Install
        run: npm install
    
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run run-all
          record: true
          parallel: true
        env: 
         CYPRESS_RECORD_KEY: 2e62183d-0bf2-4bfd-8d81-602ac53e1b40
         GITHUB_TOKEN: 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
